### ISSUE TITLE
Kanban board setting review

### ISSUE THREAD

**Issue by ameerhamzakhalid** [ameerhamzakhalid/capstone-javascript#25]
### **Kanban Board**

Link of the repository GitHub:
https://github.com/ameerhamzakhalid/capstone-javascript/

Link to the project group Kanban
https://github.com/ameerhamzakhalid/capstone-javascript/projects/1

We are two students:
-     Student A: [@ameerhamzakhalid ](https://github.com/ameerhamzakhalid)
-     Student B: [@asifaminisonline ](https://github.com/asifaminisonline)

**Comment by Kossi-stack** [comment]
- [x] Kindly assign the tasks to each student so that their profile will appear beside the tasks

**Comment by ameerhamzakhalid** [comment]
done

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @ameerhamzakhalid, and @asifaminisonline👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
